export const GAME_DEVELOPMENT_DATA = [
  {
    gameId: "001",
    title: "Tramponline Trample",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/trampoline-trample",
  },
  {
    gameId: "002",
    title: "Savage Wars",
    thumbnail: "",
    description: "",
    link: "",
  },
  {
    gameId: "003",
    title: "Raido: Road to Ragnarok",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/raido-alpha-build",
  },
  {
    gameId: "004",
    title: "Prototype: Drop",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/drop-2018-alpha",
  },
  {
    gameId: "005",
    title: "Prototype: RTS",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/rts-prototype",
  },
  {
    gameId: "006",
    title: "Prototype: City Destroyer",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/city-destroyer-prototype",
  },
  {
    gameId: "007",
    title: "Where Are We... Chapter 0",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/where-are-we-chapter-0",
  },
  {
    gameId: "008",
    title: "Asteroid Engine",
    thumbnail: "",
    description: "",
    link: "https://danielweimer.itch.io/asteroid-engine",
  },
  {
    gameId: "009",
    title: "Prototype: Scoundrel",
    thumbnail: "",
    description: "",
    link: "https://d-weimer.github.io/scoundrel-solo-card-game/",
  },
];
