export const GAME_DEVELOPMENT_DATA = [
  {
    gameId: "001",
    type: "study",
    title: "Tramponline Trample",
    description: "",
    thumbnail: "/games/thumbnails/trampoline-trample.png",
    link: "https://danielweimer.itch.io/trampoline-trample",
  },
  {
    gameId: "002",
    type: "study",
    title: "Virtual Pet V1",
    description: "",
    thumbnail: "/thumbnails/virtual-pet-v1.png",
    link: "",
  },
  {
    gameId: "003",
    type: "card",
    title: "Savage Wars",
    description: "",
    thumbnail: "/games/thumbnails/savage-wars.png",
    link: "https://dweimer19.wixsite.com/danielweimer/single-post/2014/09/15/savage-wars-and-version-11",
  },
  {
    gameId: "004",
    type: "study",
    title: "Virtual Pet V2",
    description: "",
    thumbnail: "/thumbnails/virtual-pet-v2.png",
    link: "",
  },
  {
    gameId: "005",
    type: "card",
    title: "Raido: Road to Ragnarok",
    description: "",
    thumbnail: "/games/thumbnails/raido.png",
    link: "https://danielweimer.itch.io/raido-alpha-build",
  },
  {
    gameId: "006",
    type: "prototype",
    title: "Drop",
    description: "",
    thumbnail: "/games/thumbnails/drop.png",
    link: "https://danielweimer.itch.io/drop-2018-alpha",
  },
  {
    gameId: "007",
    type: "prototype",
    title: "Real-Time Strategy",
    description: "",
    thumbnail: "/thumbnails/rts.png",
    link: "https://danielweimer.itch.io/rts-prototype",
  },
  {
    gameId: "008",
    type: "work",
    title: "Lady Blur: Mission to Mars",
    description: "",
    thumbnail: "/thumbnails/mission-to-mars.png",
    link: "https://apkpure.com/cn/lady-blur-mission-to-mars/com.sean.ladyblur",
  },
  {
    gameId: "009",
    type: "work",
    title: "Lady Blur: Defend the Gates",
    description: "",
    thumbnail: "/thumbnails/defend-the-gates.png",
    link: "https://gamejolt.com/games/lady_blur/798592",
  },
  {
    gameId: "010",
    type: "prototype",
    title: "City Destroyer",
    description: "",
    thumbnail: "/games/thumbnails/city-destroyer.png",
    link: "https://danielweimer.itch.io/city-destroyer-prototype",
  },
  {
    gameId: "011",
    type: "study",
    title: "Where Are We... Chapter 0",
    description: "",
    thumbnail: "/games/thumbnails/where-are-we.png",
    link: "https://danielweimer.itch.io/where-are-we-chapter-0",
  },
  {
    gameId: "012",
    type: "prototype",
    title: "Dino RPG Test",
    description: "Password: rawr",
    thumbnail: "/games/thumbnails/dino-test.png",
    link: "https://danielweimer.itch.io/dino-test",
  },
  {
    gameId: "013",
    type: "study",
    title: "Action RPG Demo",
    description: "",
    thumbnail: "/thumbnails/arpg.png",
    link: "https://danielweimer.itch.io/iga2-arpg-demo",
  },
  {
    gameId: "014",
    type: "prototype",
    title: "Asteroid Engine",
    description: "",
    thumbnail: "/games/thumbnails/asteroid-engine.png",
    link: "https://danielweimer.itch.io/asteroid-engine",
  },
  {
    gameId: "015",
    type: "card",
    title: "Scoundrel",
    description: "",
    thumbnail: "/games/thumbnails/scoundrel.png",
    link: "https://d-weimer.github.io/scoundrel-solo-card-game/",
  },
];
