export const SOFTWARE_PROJECT_DATA = [
  {
    projectId: "001",
    title: "Triple Peaks Library website",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
  {
    projectId: "002",
    title: "Triple Peaks Cafe website",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
  {
    projectId: "003",
    title: "Spots",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
  {
    projectId: "004",
    title: "WTWR (What To Wear?)",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
  {
    projectId: "005",
    title: "News Explorer",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
  {
    projectId: "006",
    title: "The Nugget App",
    thumbnail: "",
    shortDescription: "",
    media: [],
    longDescription: "",
    link: "",
  },
];
