export const SOFTWARE_PROJECT_DATA = [
  {
    projectId: "001",
    title: "Triple Peaks Library",
    thumbnail: "/projects/logos/triple-peaks-library-logo.png",
    shortDescription: "Triple Peaks Library website",
    fullDescription: "",
    media: [
      {
        path: "/projects/media/triple-peaks-library/triple-peaks-library-01.png",
        caption: "Triple Peaks Library",
      },
      {
        path: "/projects/media/triple-peaks-library/triple-peaks-library-02.png",
        caption: "Triple Peaks Library - Upcoming events",
      },
      {
        path: "/projects/media/triple-peaks-library/triple-peaks-library-03.png",
        caption: "Triple Peaks Library - Staff picks",
      },
      {
        path: "/projects/media/triple-peaks-library/triple-peaks-library-04.png",
        caption: "Triple Peaks Library - About the library",
      },
    ],
    link: "https://codepen.io/Daniel-Weimer/full/WbwvBqp",
  },
  {
    projectId: "002",
    title: "Triple Peaks Cafe",
    thumbnail: "/projects/logos/triple-peaks-cafe-logo.png",
    shortDescription: "Triple Peaks Cafe website",
    fullDescription: "",
    media: [{ path: "", caption: "" }],
    link: "https://codepen.io/Daniel-Weimer/full/JoXrRqX",
  },
  {
    projectId: "003",
    title: "Spots",
    thumbnail: "/projects/logos/spots-logo.png",
    shortDescription: "Spots Social Media app",
    fullDescription: "",
    media: [{ path: "", caption: "" }],
    link: "https://d-weimer.github.io/se_project_spots/",
  },
  {
    projectId: "004",
    title: "WTWR (What To Wear?)",
    thumbnail: "/projects/logos/wtwr-logo.png",
    shortDescription: "WTWR (What To Wear?) Weather app",
    fullDescription: "",
    media: [{ path: "", caption: "" }],
    link: "https://djw-wtwr.jumpingcrab.com/",
  },
  {
    projectId: "005",
    title: "News Explorer",
    thumbnail: "/projects/logos/news-explorer-logo.png",
    shortDescription: "News Explorer app",
    fullDescription: "",
    media: [{ path: "", caption: "" }],
    link: "https://djw-newsexplorer.jumpingcrab.com/",
  },
  {
    projectId: "006",
    title: "The Nugget App",
    thumbnail: "/projects/logos/the-nugget-app-logo.png",
    shortDescription: "The Nugget App",
    fullDescription: "",
    media: [{ path: "", caption: "" }],
    link: "https://www.linkedin.com/in/daniel-weimer/overlay/Position/3007284270/treasury/?profileId=ACoAAAyP3pgBiPoYh2P53hY6ITRaVku-ijg3PWw",
  },
];
