export const SOFTWARE_PROJECT_DATA = [
  {
    projectId: "001",
    title: "Triple Peaks Library website",
    thumbnail: "/projects/triple-peaks-library-logo.png",
    shortDescription: "Triple Peaks Library website",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "https://codepen.io/Daniel-Weimer/full/WbwvBqp",
  },
  {
    projectId: "002",
    title: "Triple Peaks Cafe website",
    thumbnail: "/projects/triple-peaks-cafe-logo.png",
    shortDescription: "Triple Peaks Cafe website",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "https://codepen.io/Daniel-Weimer/full/JoXrRqX",
  },
  {
    projectId: "003",
    title: "Spots",
    thumbnail: "/projects/spots-logo.png",
    shortDescription: "Spots",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "https://d-weimer.github.io/se_project_spots/",
  },
  {
    projectId: "004",
    title: "WTWR (What To Wear?)",
    thumbnail: "/projects/wtwr-logo.png",
    shortDescription: "WTWR (What To Wear?)",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "https://djw-wtwr.jumpingcrab.com/",
  },
  {
    projectId: "005",
    title: "News Explorer",
    thumbnail: "/projects/news-explorer-logo.png",
    shortDescription: "News Explorer",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "https://djw-newsexplorer.jumpingcrab.com/",
  },
  {
    projectId: "006",
    title: "The Nugget App",
    thumbnail: "/projects/the-nugget-app-logo.png",
    shortDescription: "The Nugget App",
    fullDescription: "",
    media: [{ type: "", path: "" }],
    link: "",
  },
];
